version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis_cache
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgres://postgres:password@db:5432/mydatabase
      - REDIS_URL=redis://redis_cache:6379/0
      - REDIS_CACHE_URL=redis://redis_cache:6379/1

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_URL=http://localhost:3000

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp_development
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis_cache:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  sidekiq:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ["bundle", "exec", "sidekiq"]
    volumes:
      - ./backend:/app
    depends_on:
      - backend
      - redis_cache
    environment:
      - RAILS_ENV=development
      - REDIS_URL=redis://redis_cache:6379/0
      - DATABASE_URL=postgres://postgres:password@db:5432/mydatabase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
      - POSTGRES_HOST=db

volumes:
  pg_data:
